"""empty message

Revision ID: 28a4fb2187f8
Revises: ed4af22ab75a
Create Date: 2021-05-11 15:17:32.813231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a4fb2187f8'
down_revision = 'ed4af22ab75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['uid'], ['id'])
    op.create_index(op.f('ix_member_mobile'), 'member', ['mobile'], unique=False)
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_index(op.f('ix_member_mobile'), table_name='member')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
